shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - SDelete-Gui\packages

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  pfx_password:
    secure: yfky3xGsKE0Kwe2xOHB2sQ==

artifacts:
  - path: '**\SDelete-Gui.exe'
