shallow_clone: true

# version format
version: 1.0.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

cache:
  - SDelete-Gui\packages

configuration: Release

# Assembly Info
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"


environment:
  pfx_password:
    secure: yfky3xGsKE0Kwe2xOHB2sQ==


after_build:
  - "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe" sign /t http://timestamp.verisign.com/scripts/timstamp.dll /sha1 b6c83dfa006475aec9e458a48696c1c42ff1b5c4 "C:\projects\sdelete-gui\SDelete-Gui\bin\Release\SDelete-Gui.exe"

artifacts:
  - path: '**\bin\Release\SDelete-Gui.exe'
    name: SDelete-Gui.exe
